In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

C:\Users\psych\AppData\Roaming\Python\Python311\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\psych\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [2]:
df = pd.read_csv('./Datasets/std_marks_data.csv')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   hours     288 non-null    float64
 1   age       300 non-null    int64
 2   internet  300 non-null    int64
 3   marks     300 non-null    float64
dtypes: float64(2), int64(2)
memory usage: 9.5 KB

In [4]:
df.isna().sum()

hours       12
age          0
internet     0
marks        0
dtype: int64

In [5]:
df.fillna(df['hours'].mean(), inplace= True)

        hours  age  internet  marks
0    6.840000   15         0  78.64
1    6.560000   20         1  88.80
2    5.494514   21         1  88.90
3    8.670000   22         1  98.99
4    7.550000   17         1  92.34
..        ...  ...       ...    ...
295  2.990000   25         0  43.45
296  6.550000   15         1  77.74
297  0.000000   20         1  75.76
298  9.900000   22         0  99.99
299  3.400000   21         0  99.99

[300 rows x 4 columns]

In [6]:
df.isna().sum()

hours       0
age         0
internet    0
marks       0
dtype: int64

In [7]:
X = df[['hours', 'age', 'internet']]
y = df['marks']

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((240, 3), (60, 3), (240,), (60,))

In [9]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(X_train, y_train)

LinearRegression()

In [10]:
y_pred = mlr.predict(X_test)

In [11]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print(f"Mean Squared Error: {mse}")
print(F"Root Mean Squared Error: {rmse}")

Mean Squared Error: 296.9278739472545
Root Mean Squared Error: 17.2315952235205

Does adding more features always improve a regression model's accuracy ?

- No, It does not improve accuracy every time, In some cases it causes increase in dimensionality but not participate in prediction which causes problem like curse of dimensionality.

In [12]:
df['marks'].unique()

array([78.64, 88.8 , 88.9 , 98.99, 92.34, 50.3 , 43.45, 77.74, 75.76,
       66.67, 78.88, 53.34, 55.9 , 82.78, 75.99, 99.99])

In [13]:
binary_fn = lambda x: 0 if x < 50 else 1
df['Binary'] = df['marks'].apply(binary_fn)

In [14]:
df[df['Binary'] == 0].count()

hours       22
age         22
internet    22
marks       22
Binary      22
dtype: int64

In [15]:
df[df['Binary'] == 1].count()

hours       278
age         278
internet    278
marks       278
Binary      278
dtype: int64

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   hours     300 non-null    float64
 1   age       300 non-null    int64
 2   internet  300 non-null    int64
 3   marks     300 non-null    float64
 4   Binary    300 non-null    int64
dtypes: float64(2), int64(3)
memory usage: 11.8 KB

In [17]:
df.Binary.unique()

array([1, 0], dtype=int64)

In [18]:
X = df[['hours', 'age', 'internet']]
y = df['Binary']

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((240, 3), (60, 3), (240,), (60,))

In [20]:
from sklearn.svm import SVC
svc = SVC(kernel= 'linear')
svc.fit(X_train, y_train)

SVC(kernel='linear')

In [21]:
y_pred = svc.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print(f"Mean Squared Error: {mse}")
print(F"Root Mean Squared Error: {rmse}")

Mean Squared Error: 0.11666666666666667
Root Mean Squared Error: 0.3415650255319866

In [22]:
df = pd.read_csv('Datasets/House Price India.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14620 entries, 0 to 14619
Data columns (total 23 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     14620 non-null  int64
 1   Date                                   14620 non-null  int64
 2   number of bedrooms                     14620 non-null  int64
 3   number of bathrooms                    14620 non-null  float64
 4   living area                            14620 non-null  int64
 5   lot area                               14620 non-null  int64
 6   number of floors                       14620 non-null  float64
 7   waterfront present                     14620 non-null  int64
 8   number of views                        14620 non-null  int64
 9   condition of the house                 14620 non-null  int64
 10  grade of the house                     14620 non-null  int64
 11  Area of the house(excluding basement)  14620 non-null  int64
 12  Area of the basement                   14620 non-null  int64
 13  Built Year                             14620 non-null  int64
 14  Renovation Year                        14620 non-null  int64
 15  Postal Code                            14620 non-null  int64
 16  Lattitude                              14620 non-null  float64
 17  Longitude                              14620 non-null  float64
 18  living_area_renov                      14620 non-null  int64
 19  lot_area_renov                         14620 non-null  int64
 20  Number of schools nearby               14620 non-null  int64
 21  Distance from the airport              14620 non-null  int64
 22  Price                                  14620 non-null  int64
dtypes: float64(4), int64(19)
memory usage: 2.6 MB

In [23]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

from sklearn.linear_model import Lasso

model = Lasso(alpha= 1)

In [24]:
df['Price'].unique()

array([2380000, 1400000, 1200000, ...,  221700,  219200,  146000],
      dtype=int64)

In [25]:
Price_clf_fn = lambda x : 0 if x > 200000 else 1

In [26]:
df['Price_clf'] = df['Price'].apply(Price_clf_fn)

In [27]:
df.drop('Price', axis= 1, inplace= True)

In [28]:
df.head()

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price_clf
0,6762810145,42491,5,2.50,3650,9050,2.0,0,4,5,...,1921,0,122003,52.8645,-114.557,2880,5400,2,58,0
1,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,0
2,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,0
3,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,0
4,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,0

In [29]:
df.drop('Date', inplace= True, axis= 1)
df.drop('id', inplace= True, axis= 1)

In [30]:
X = df.iloc[:,:-1]
y = df['Price_clf']

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 42)

In [32]:
model.fit(X_train, y_train)

Lasso(alpha=1)

In [33]:
y.unique()

array([0, 1], dtype=int64)

In [34]:
y_pred = model.predict(X_test)

In [35]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

accuracy = accuracy_score(y_test, y_pred.round())
confusion = confusion_matrix(y_test, y_pred.round())
classification = classification_report(y_test, y_pred.round())

In [36]:
print(f"Accuracy: {accuracy}\n")
print(f"Confusion Matrix:\n{confusion}")
print(f"\nClassification Report: {classification}")

Accuracy: 0.9610123119015048

Confusion Matrix:
[[2810    0]
 [ 114    0]]

Classification Report:               precision    recall  f1-score   support

           0       0.96      1.00      0.98      2810
           1       0.00      0.00      0.00       114

    accuracy                           0.96      2924
   macro avg       0.48      0.50      0.49      2924
weighted avg       0.92      0.96      0.94      2924